/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as PodcastIdRouteImport } from './routes/podcast/$id'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIdRoute = PodcastIdRouteImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/podcast/$id': typeof PodcastIdRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesByTo {
  '/podcast/$id': typeof PodcastIdRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/podcast/$id': typeof PodcastIdRoute
  '/(home)/': typeof homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/podcast/$id' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/podcast/$id' | '/'
  id: '__root__' | '/podcast/$id' | '/(home)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PodcastIdRoute: typeof PodcastIdRoute
  homeIndexRoute: typeof homeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$id': {
      id: '/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof PodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PodcastIdRoute: PodcastIdRoute,
  homeIndexRoute: homeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
