/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index/route'
import { Route as PodcastIdImport } from './routes/podcast/$id'

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PodcastIdRoute = PodcastIdImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/podcast/$id': {
      id: '/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof PodcastIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/podcast/$id': typeof PodcastIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/podcast/$id': typeof PodcastIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/podcast/$id': typeof PodcastIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/podcast/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/podcast/$id'
  id: '__root__' | '/' | '/podcast/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  PodcastIdRoute: typeof PodcastIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  PodcastIdRoute: PodcastIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/podcast/$id"
      ]
    },
    "/": {
      "filePath": "index/route.tsx"
    },
    "/podcast/$id": {
      "filePath": "podcast/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
